/**
 * @module commands/completion
 *
 * `vibe completion <shell>` — emit a shell completion script for the
 * given shell (zsh / bash / fish). The script is generated by walking
 * the live Commander program tree, so completion stays in sync with
 * the actual command set without a parallel manifest.
 *
 * Install:
 *   zsh:  vibe completion zsh  >> ~/.zsh/completions/_vibe   (then add the dir to fpath)
 *         or:  echo 'eval "$(vibe completion zsh)"' >> ~/.zshrc
 *   bash: echo 'eval "$(vibe completion bash)"' >> ~/.bashrc
 *   fish: vibe completion fish > ~/.config/fish/completions/vibe.fish
 *
 * Cost tiers ride along in zsh descriptions (e.g.
 * "[VERY-HIGH] Generate video …") so the user sees the price tag at
 * tab-completion time, not just in --help.
 */

import { Command } from "commander";
import { exitWithError, usageError } from "./output.js";
import { getCostTier, type CostTier } from "./_shared/cost-tier.js";

export const completionCommand = new Command("completion")
  .description("Print a shell completion script for `vibe`")
  .argument("<shell>", "Target shell: zsh | bash | fish")
  .addHelpText(
    "after",
    `
Examples:
  $ vibe completion zsh  >> ~/.zsh/completions/_vibe   # then ensure that dir is in fpath
  $ echo 'eval "$(vibe completion bash)"' >> ~/.bashrc
  $ vibe completion fish > ~/.config/fish/completions/vibe.fish

The output is generated from the live command tree, so it stays in
sync with the CLI surface. Re-run after upgrades.
`,
  )
  .action((shell: string) => {
    const program = completionCommand.parent;
    if (!program) {
      exitWithError(usageError("completion: program tree not available"));
    }

    const valid = new Set(["zsh", "bash", "fish"]);
    if (!valid.has(shell)) {
      exitWithError(usageError(`Unknown shell: ${shell}`, "Supported: zsh, bash, fish"));
    }

    if (shell === "zsh") console.log(generateZsh(program));
    else if (shell === "bash") console.log(generateBash(program));
    else console.log(generateFish(program));
  });

interface CommandNode {
  /** Top-level name (e.g. `generate`). */
  name: string;
  description: string;
  cost?: CostTier;
  subcommands: Array<{ name: string; description: string; cost?: CostTier }>;
}

/**
 * Walk the program tree into a flat description suitable for shell-script
 * emission. Skips deprecated commands (description contains "deprecated")
 * and meta commands like `help`. Hidden commands are included so
 * `vibe project <tab>` still works for power users — they were only
 * hidden from the front-page `--help`, not from the catalog.
 */
function collectCommandTree(program: Command): CommandNode[] {
  const skipTopLevel = new Set(["help"]);
  const nodes: CommandNode[] = [];
  for (const top of program.commands) {
    const name = top.name();
    if (skipTopLevel.has(name)) continue;
    const desc = top.description() || "";
    if (desc.toLowerCase().includes("deprecated")) continue;
    const subs = top.commands
      .filter((s) => !(s.description() || "").toLowerCase().includes("deprecated"))
      .map((s) => ({
        name: s.name(),
        description: s.description() || "",
        cost: getCostTier(s),
      }));
    nodes.push({ name, description: desc, cost: getCostTier(top), subcommands: subs });
  }
  return nodes;
}

function tierBadge(cost: CostTier | undefined): string {
  if (!cost) return "";
  return `[${cost.toUpperCase()}] `;
}

/** Sanitize description for shell single-quoted strings. */
function shellEscape(s: string): string {
  // For both zsh and bash _describe / complete usage, single-quote the
  // value and double any embedded single quotes. Strip newlines too —
  // multi-line descriptions confuse the completion engine.
  return s.replace(/\n/g, " ").replace(/\s+/g, " ").trim().replace(/'/g, "'\"'\"'");
}

// ── zsh ────────────────────────────────────────────────────────────────────

function generateZsh(program: Command): string {
  const nodes = collectCommandTree(program);

  const topLines = nodes
    .map((n) => `'${n.name}:${shellEscape(tierBadge(n.cost) + n.description)}'`)
    .join(" \\\n    ");

  const subBlocks = nodes
    .filter((n) => n.subcommands.length > 0)
    .map((n) => {
      const subs = n.subcommands
        .map((s) => `'${s.name}:${shellEscape(tierBadge(s.cost) + s.description)}'`)
        .join(" \\\n        ");
      return `    ${n.name})
        local -a subcommands
        subcommands=(
        ${subs}
        )
        _describe 'subcommand' subcommands
        ;;`;
    })
    .join("\n");

  return `#compdef vibe
# vibe shell completion for zsh — generated by \`vibe completion zsh\`.
# Re-run after upgrades; the script reflects the live command tree.

_vibe() {
  local -a commands
  commands=(
    ${topLines}
  )

  _arguments -C \\
    '1: :->cmd' \\
    '*:: :->args'

  case $state in
    cmd)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
${subBlocks}
      esac
      ;;
  esac
}

_vibe "$@"
`;
}

// ── bash ───────────────────────────────────────────────────────────────────

function generateBash(program: Command): string {
  const nodes = collectCommandTree(program);

  const topNames = nodes.map((n) => n.name).join(" ");

  const subCases = nodes
    .filter((n) => n.subcommands.length > 0)
    .map((n) => {
      const names = n.subcommands.map((s) => s.name).join(" ");
      return `    ${n.name})
      COMPREPLY=( $(compgen -W "${names}" -- "$cur") )
      ;;`;
    })
    .join("\n");

  return `# vibe shell completion for bash — generated by \`vibe completion bash\`.
# Re-run after upgrades; the script reflects the live command tree.
# Bash completions are word-only — no description hints — so consider
# zsh or fish for richer feedback.

_vibe_complete() {
  local cur prev cmd
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]}"

  if [[ $COMP_CWORD == 1 ]]; then
    COMPREPLY=( $(compgen -W "${topNames}" -- "$cur") )
    return 0
  fi

  case "$cmd" in
${subCases}
    *)
      COMPREPLY=()
      ;;
  esac
}

complete -F _vibe_complete vibe
`;
}

// ── fish ───────────────────────────────────────────────────────────────────

function generateFish(program: Command): string {
  const nodes = collectCommandTree(program);

  const lines: string[] = [
    "# vibe shell completion for fish — generated by `vibe completion fish`.",
    "# Re-run after upgrades; the script reflects the live command tree.",
    "",
    "complete -c vibe -f",
    "",
  ];

  // Top-level commands (only when no subcommand has been typed yet).
  for (const n of nodes) {
    const desc = shellEscape(tierBadge(n.cost) + n.description);
    lines.push(`complete -c vibe -n '__fish_use_subcommand' -a '${n.name}' -d '${desc}'`);
  }
  lines.push("");

  // Subcommand completions, scoped via `__fish_seen_subcommand_from`.
  for (const n of nodes) {
    if (n.subcommands.length === 0) continue;
    for (const s of n.subcommands) {
      const desc = shellEscape(tierBadge(s.cost) + s.description);
      lines.push(
        `complete -c vibe -n '__fish_seen_subcommand_from ${n.name}' -a '${s.name}' -d '${desc}'`,
      );
    }
  }

  return lines.join("\n") + "\n";
}
