/**
 * @module _shared/scene-audio-scan
 *
 * Reads a scene project's root + sub-composition HTML and returns a flat list
 * of audio elements with **absolute** timeline positions. Used by `executeSceneRender`
 * to mux narration / background-audio tracks into the producer's silent video
 * output via ffmpeg.
 *
 * Why a post-render scanner: at time of writing, `@hyperframes/producer`
 * renders frames + assembles the MP4 but does not embed audio from
 * `<audio>` elements that live inside sub-compositions. We pick up the slack
 * here without touching the producer.
 *
 * Pure module — no I/O beyond the explicit `loadCompositionHtml` reader the
 * orchestrator passes in. Easy to unit-test with fixture strings.
 */

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * One `<audio>` element resolved into an absolute-timeline entry.
 */
export interface SceneAudioElement {
  /** Project-relative `src` from the audio tag (e.g. `assets/narration-intro.wav`). */
  srcRel: string;
  /** Absolute path on disk — `resolve(projectDir, srcRel)`. */
  srcAbs: string;
  /** Seconds from the start of the root timeline at which playback begins. */
  absoluteStart: number;
  /**
   * Composition-supplied duration. `"auto"` means "use the file's natural
   * duration"; the mux pass probes the file. Numeric means a hard cap.
   */
  durationHint: "auto" | number;
  /** Cap from the parent scene clip — audio is trimmed to fit this many seconds. */
  clipDurationCap: number;
  /** `data-volume`. Defaults to `1`. */
  volume: number;
  /** `data-track-index` — used so callers can group narration vs music vs etc. */
  trackIndex: number;
  /** Composition that owns this audio element (debug aid). */
  compositionSrc: string;
}

/**
 * Parsed view of a single `<div class="clip" data-composition-src="...">`
 * reference inside the root composition.
 */
export interface SceneClipRef {
  compositionId: string;
  compositionSrc: string;
  start: number;
  duration: number;
  trackIndex: number;
}

/**
 * Walk the root HTML for clip references. Returns one entry per
 * `<div class="clip">` with the four attributes we care about. Pure: a
 * regex-based scan, not a full DOM parser. The root file is generated by
 * VibeFrame so the markup is predictable; if a user hand-edits it into
 * something unparseable, the scanner simply finds fewer clips.
 */
export function parseRootClips(rootHtml: string): SceneClipRef[] {
  const clips: SceneClipRef[] = [];
  // Anchor on `class="clip"` and pull every relevant data attribute that
  // appears in the same opening tag. Attribute order is not assumed.
  const clipRegex = /<div\b[^>]*class="clip"[^>]*>/gi;
  let match: RegExpExecArray | null;
  while ((match = clipRegex.exec(rootHtml)) !== null) {
    const tag = match[0];
    const compositionId = pickAttr(tag, "data-composition-id");
    const compositionSrc = pickAttr(tag, "data-composition-src");
    const start = pickNumberAttr(tag, "data-start");
    const duration = pickNumberAttr(tag, "data-duration");
    const trackIndex = pickNumberAttr(tag, "data-track-index") ?? 1;
    if (!compositionId || !compositionSrc || start === null || duration === null) {
      continue;
    }
    clips.push({ compositionId, compositionSrc, start, duration, trackIndex });
  }
  return clips;
}

/**
 * Walk a single composition's HTML for `<audio>` elements. Returns one entry
 * per element with attributes resolved into our shape. Composition-local —
 * caller adds the parent clip's start to compute absolute timing.
 */
export function parseSceneAudios(
  compositionHtml: string,
): Array<{
  srcRel: string;
  localStart: number;
  durationHint: "auto" | number;
  volume: number;
  trackIndex: number;
}> {
  const out: Array<{
    srcRel: string;
    localStart: number;
    durationHint: "auto" | number;
    volume: number;
    trackIndex: number;
  }> = [];

  // `<audio>` opens may span multiple lines in our emitted HTML; capture the
  // full open tag (everything up to `>`).
  const audioRegex = /<audio\b([^>]*)>/gi;
  let match: RegExpExecArray | null;
  while ((match = audioRegex.exec(compositionHtml)) !== null) {
    const attrs = match[1];
    const src = pickAttr(attrs, "src");
    if (!src) continue;
    const localStart = pickNumberAttr(attrs, "data-start") ?? 0;
    const durationRaw = pickAttr(attrs, "data-duration");
    const durationHint: "auto" | number =
      !durationRaw || durationRaw === "auto"
        ? "auto"
        : Number(durationRaw);
    const volume = pickNumberAttr(attrs, "data-volume") ?? 1;
    const trackIndex = pickNumberAttr(attrs, "data-track-index") ?? 2;
    out.push({ srcRel: src, localStart, durationHint, volume, trackIndex });
  }
  return out;
}

/** Reader hook so the scanner stays unit-testable without touching the FS. */
export type CompositionReader = (compositionSrcRel: string) => Promise<string | null>;

/**
 * Default reader: read the composition file from disk relative to the
 * project directory. Returns `null` for missing files so the scanner can
 * skip them and continue.
 */
export function makeFsCompositionReader(projectDir: string): CompositionReader {
  return async (compositionSrcRel: string): Promise<string | null> => {
    const abs = resolve(projectDir, compositionSrcRel);
    try {
      return await readFile(abs, "utf-8");
    } catch {
      return null;
    }
  };
}

/**
 * Top-level scan. Parses every clip in the root, loads each composition,
 * pulls every audio element, and resolves absolute timeline positions.
 *
 * Audio absolute start = clip.start + audio.localStart. The `clipDurationCap`
 * is filled in from the clip's own duration so the mux pass can trim audio
 * that runs past the visual end of its parent scene.
 */
export async function scanSceneAudio(opts: {
  projectDir: string;
  rootHtml: string;
  /** Override the default FS reader (testing). */
  readComposition?: CompositionReader;
}): Promise<SceneAudioElement[]> {
  const reader = opts.readComposition ?? makeFsCompositionReader(opts.projectDir);
  const clips = parseRootClips(opts.rootHtml);

  const out: SceneAudioElement[] = [];

  // Sub-composition scan — original v0.55 behaviour. Each clip's source
  // HTML is read for `<audio>` elements; their `data-start` is relative
  // to the clip start, so `absoluteStart = clip.start + audio.localStart`.
  for (const clip of clips) {
    const html = await reader(clip.compositionSrc);
    if (!html) continue;
    const audios = parseSceneAudios(html);
    for (const audio of audios) {
      out.push({
        srcRel: audio.srcRel,
        srcAbs: resolve(opts.projectDir, audio.srcRel),
        absoluteStart: clip.start + audio.localStart,
        durationHint: audio.durationHint,
        clipDurationCap: clip.duration - audio.localStart,
        volume: audio.volume,
        trackIndex: audio.trackIndex,
        compositionSrc: clip.compositionSrc,
      });
    }
  }

  // v0.63: also scan root-level `<audio>` elements. `vibe scene build`
  // writes narration `<audio>` tags directly into the root composition
  // alongside the auto-generated clip refs (because injecting them into
  // each scene HTML — written by an LLM via compose-scenes-with-skills —
  // would require mutating LLM output and races with regeneration). At
  // root level, `data-start` is absolute, and the cap defaults to the
  // longest known clip end so producer trims don't surprise the caller.
  const maxClipEnd = clips.reduce((m, c) => Math.max(m, c.start + c.duration), 0);
  const rootAudios = parseSceneAudios(opts.rootHtml);
  for (const audio of rootAudios) {
    out.push({
      srcRel: audio.srcRel,
      srcAbs: resolve(opts.projectDir, audio.srcRel),
      absoluteStart: audio.localStart,
      durationHint: audio.durationHint,
      clipDurationCap: Math.max(0, maxClipEnd - audio.localStart),
      volume: audio.volume,
      trackIndex: audio.trackIndex,
      compositionSrc: "(root)",
    });
  }

  // Stable sort by absolute start so downstream filter graphs are deterministic.
  out.sort((a, b) => a.absoluteStart - b.absoluteStart);
  return out;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pickAttr(tag: string, name: string): string | null {
  // Allow either single or double quotes; tolerate whitespace around `=`.
  const re = new RegExp(`\\b${escapeRegex(name)}\\s*=\\s*("([^"]*)"|'([^']*)')`);
  const m = tag.match(re);
  if (!m) return null;
  return m[2] ?? m[3] ?? null;
}

function pickNumberAttr(tag: string, name: string): number | null {
  const raw = pickAttr(tag, name);
  if (raw === null) return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
